TRAIN_MARKED_TO_NEXT_SAMPLE = False

ATTENTION_WINDOW_SIZE = 512
ATTENTION_WINDOW_LOOKBACK = 3
ATTENTION_DROPOUT = 0.2

START_LR = 1e-10
MAX_LR = 1e-5
WARMUP_PERIOD = 4
L2_REG_WEIGHT_DECAY = 0.004
EARLY_LOSS_EXIT_LOOKBACK = 2
EARLY_LOSS_EXIT = 3
REDUCE_LR_PATIENCE = 1
REDUCE_LR_FACTOR = 0.6
# Set high because not in use at the moment
STEP_SIZE = 1_000_000
STEP_GAMMA = 0.9

NUM_ATTENTION_LAYERS = 10
FEED_FORWARD_HDIM = 2048

WINDOW_SIZE = 128
