#!/usr/bin/env bash
python3 predictor/src/Predictor.py --mode train --training-data ~/scratch/training-data --test-data ~/scratch/test_data --model-dir ./local.model/ --output-path /tmp/ | tee -a training-log
