#!/usr/bin/env bash
BASE="$1"
#echo "Basename: $(dirname "$1")"
NEW_NAME=$(dirname "$1" | shasum | awk '{ print $1 }')
echo "New name: ${NEW_NAME}"
echo "Converting $1 to $2/${NEW_NAME}_$3"
./emulator/target/release/recording_to_file --file "$1" --output "$2/${NEW_NAME}_$3"
