#!/usr/bin/env bash
./scripts/build
find "$1" -name "*.gbs" -print0 | xargs -0 -I {} -P 24 timeout 10m ./scripts/play_and_record_gbs "{}"
find "$1" -name "*.gbr" -print0 | xargs -0 -I {} -P 24 timeout 10m ./scripts/play_and_record_gbs "{}"
