#!/usr/bin/env bash
python3 predictor/src/Predictor.py --mode fresh --training-data ~/gb-sounds/training-data --test-data ~/gb-sounds/testing-data --model-dir ./local.model/ --output-path /tmp/ | tee -a training-log
